### ISSUE TITLE
Request: choose wallpaper fit mode

### ISSUE THREAD

**Issue by garyee** [muhammadmuzzammil1998/BingWallpaper#1]
Hi,

thanks for your work. I have just one small request. Would it be possible to make the picture fit-mode configurable?

![Windows-10-Personalization-Background-Options](https://user-images.githubusercontent.com/5537949/65859732-21d21c80-e369-11e9-8240-7626351b5885.jpg)

**Comment by muhammadmuzzammil1998** [comment]
Hi Gerald!

This application is long overdue for a re-write to improve functionality. I will make this in a Graphical User Interface. Thanks for this. I will include this in it.
